[package]
name = "roguelike"
version = "0.1.0"
authors = ["Paul Sanford <me@paulsanford.net>"]

[dependencies]
tcod = { version = "0.10", features = ["rustc-serialize"] }
rand = "0.3.9"
rustc-serialize = "0.3"
